// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.23.4
// source: service_aaa.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Method1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Something string `protobuf:"bytes,1,opt,name=something,proto3" json:"something,omitempty"`
}

func (x *Method1Request) Reset() {
	*x = Method1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_aaa_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method1Request) ProtoMessage() {}

func (x *Method1Request) ProtoReflect() protoreflect.Message {
	mi := &file_service_aaa_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method1Request.ProtoReflect.Descriptor instead.
func (*Method1Request) Descriptor() ([]byte, []int) {
	return file_service_aaa_proto_rawDescGZIP(), []int{0}
}

func (x *Method1Request) GetSomething() string {
	if x != nil {
		return x.Something
	}
	return ""
}

type Method1Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *Method1Reply) Reset() {
	*x = Method1Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_aaa_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method1Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method1Reply) ProtoMessage() {}

func (x *Method1Reply) ProtoReflect() protoreflect.Message {
	mi := &file_service_aaa_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method1Reply.ProtoReflect.Descriptor instead.
func (*Method1Reply) Descriptor() ([]byte, []int) {
	return file_service_aaa_proto_rawDescGZIP(), []int{1}
}

func (x *Method1Reply) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_service_aaa_proto protoreflect.FileDescriptor

var file_service_aaa_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x61, 0x61, 0x61, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x2e, 0x0a,
	0x0e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x22, 0x1e, 0x0a,
	0x0c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x49, 0x0a,
	0x0a, 0x41, 0x41, 0x41, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x07, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x12, 0x18, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x31, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_service_aaa_proto_rawDescOnce sync.Once
	file_service_aaa_proto_rawDescData = file_service_aaa_proto_rawDesc
)

func file_service_aaa_proto_rawDescGZIP() []byte {
	file_service_aaa_proto_rawDescOnce.Do(func() {
		file_service_aaa_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_aaa_proto_rawDescData)
	})
	return file_service_aaa_proto_rawDescData
}

var file_service_aaa_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_aaa_proto_goTypes = []interface{}{
	(*Method1Request)(nil), // 0: services.Method1Request
	(*Method1Reply)(nil),   // 1: services.Method1Reply
}
var file_service_aaa_proto_depIdxs = []int32{
	0, // 0: services.AAAService.Method1:input_type -> services.Method1Request
	1, // 1: services.AAAService.Method1:output_type -> services.Method1Reply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_aaa_proto_init() }
func file_service_aaa_proto_init() {
	if File_service_aaa_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_aaa_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_aaa_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method1Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_aaa_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_aaa_proto_goTypes,
		DependencyIndexes: file_service_aaa_proto_depIdxs,
		MessageInfos:      file_service_aaa_proto_msgTypes,
	}.Build()
	File_service_aaa_proto = out.File
	file_service_aaa_proto_rawDesc = nil
	file_service_aaa_proto_goTypes = nil
	file_service_aaa_proto_depIdxs = nil
}
